system:
  phase_models: ../phase_models.json      # path to the phases file
  datasets: ../input-data  # path to the directory containing input data
  tags:
    dft:
      excluded_model_contributions: ['idmix', 'mag']
    estimated-entropy:
      excluded_model_contributions: ['idmix', 'mag']
output:
  output_db: Cu-Mg-mcmc.tdb               # what to name the output TDB file
  verbosity: 2                            # levels of verbosity. Choose 0, 1 or 2 for Warnings, Info, or Debug
  tracefile: null  # don't write out this file
  probfile:  null  # don't write out this file
  logfile:   null  # write output to console
mcmc:
  iterations: 2
  save_interval: 1
  scheduler: null  # don't parallelize, just run on one core
  input_db: Cu-Mg-generated.tdb
  prior:
    name: normal
    loc_relative: 1.0
    scale_relative: 1.0
